server:
  port: 6101

spring:
  application:
    name: accreditation-service
    datasource:
      url: jdbc:mysql://localhost:3306/icar_db
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka